In [1]:
import pandas as pd
import numpy as np

In [2]:
phila_res_df = pd.read_parquet("../data/restaurant_Philadelphia.parquet")
phila_res_df

,business_id,name,city,state,stars,review_count,is_open,attributes,categories
0,MTSW4McQd7CbVtyjqoe9mw,St Honore Pastries,Philadelphia,PA,4.0,80,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Food, Bubble Tea, Coffee & Tea, B..."
1,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,4.0,245,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sushi Bars, Restaurants, Japanese"
2,ROeacJQwBeh05Rqg7F6TCg,BAP,Philadelphia,PA,4.5,205,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Korean, Restaurants"
3,QdN72BWoyFypdGJhhI5r7g,Bar One,Philadelphia,PA,4.0,65,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Cocktail Bars, Bars, Italian, Nightlife, Resta..."
4,Mjboz24M9NlBeiOJKLEd_Q,DeSandro on Main,Philadelphia,PA,3.0,41,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Pizza, Restaurants, Salad, Soup"
...,...,...,...,...,...,...,...,...,...
5849,VZbkSeZtFynEascotq7ExA,Ali Baba Magic Food,Philadelphia,PA,4.0,8,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Food Stands"
5850,gPr1io7ks0Eo3FDsnDTYfg,Tata Cafe,Philadelphia,PA,4.0,21,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sandwiches, Restaurants, Italian"
5851,wVxXRFf10zTTAs11nr4xeA,PrimoHoagies,Philadelphia,PA,3.0,55,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Specialty Food, Food, Sandwiches,..."
5852,8n93L-ilMAsvwUatarykSg,Kitchen Gia,Philadelphia,PA,3.0,22,0,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Coffee & Tea, Food, Sandwiches, American (Trad..."
5853,WnT9NIzQgLlILjPT0kEcsQ,Adelita Taqueria & Restaurant,Philadelphia,PA,4.5,35,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Mexican"

In [3]:
phila_rev_df = pd.read_parquet("../data/review_Philadelphia.parquet")
phila_rev_df

,review_id,user_id,business_id,stars,useful,funny,cool,text,date
0,AqPFMleE6RsU23_auESxiA,_7bHUi9Uuf5__HHc_Q8guQ,kxX2SOes4o-D3ZQBkiMRfA,5,1,0,1,"Wow! Yummy, different, delicious. Our favo...",2015-01-04 00:01:03
1,JrIxlS1TzJ-iCu79ul40cQ,eUta8W_HdHMXPzLBBZhL1A,04UD14gamNjLY0IDYVhHJg,1,1,2,1,I am a long term frequent customer of this est...,2015-09-23 23:10:31
2,8JFGBuHMoiNDyfcxuWNtrA,smOvOajNG0lS4Pq7d8g4JQ,RZtGWDLCAtuipwaZ-UfjmQ,4,0,0,0,Good food--loved the gnocchi with marinara\nth...,2009-10-14 19:57:14
3,oyaMhzBSwfGgemSGuZCdwQ,Dd1jQj7S-BFGqRbApFzCFw,YtSqYv1Q_pOltsVPSx54SA,5,0,0,0,Tremendous service (Big shout out to Douglas) ...,2013-06-24 11:21:25
4,Xs8Z8lmKkosqW5mw_sVAoA,IQsF3Rc6IgCzjVV9DE8KXg,eFvzHawVJofxSnD7TgbZtg,5,0,0,0,My absolute favorite cafe in the city. Their b...,2014-11-12 15:30:27
...,...,...,...,...,...,...,...,...,...
687302,Wrt6pZizQzw-ZTKrvMwrGw,ua6QuBe6mar6pDrhHETzJQ,Bk_1vsPtOtO0bojfQZQIOw,2,3,3,2,"Ok, I have to say, after living on this block ...",2008-12-15 23:18:27
687303,X5R98ygOtbhryDiKA-J2qQ,LHWtjTG7e1NzNPYUbUo-9w,rgeuy1qbw6Z8B6CSVANHIA,5,1,1,1,I've been to the other Federal Donuts location...,2012-10-13 14:39:37
687304,MVg4YUQeEhCA7Z7RsBJSVg,7-7A0Avj47slLGV7yBFc8w,ytynqOUb3hjKeJfRj5Tshw,3,1,0,0,"I was so excited about all the food I saw, but...",2013-07-25 21:00:15
687305,nLjbVsETpqO17RbFcqskkA,am7-gkH_PDz598oTdYSD6A,3gVSrS4kffGGZT8oXHsIcw,3,2,0,2,"*Later Yelp* I've only been here once, but I l...",2014-11-03 14:45:46
687306,cACxcUY_AIsQKkpDRXuqnw,MCzlzlOw7IGbRAKVjJBPtg,fcGexL5VH5G2Xw0tRj9uOQ,3,1,1,0,This is a good pizza option - they deliver thr...,2018-03-13 13:54:48

## **Baseline Model: Popularity Recommendation Engine**

Display top 10 highest rated restaurant in Philadelphia

In [4]:
def compute_wr(x, m, C):            # Function to compute the weighted rating for restaurant based on existing dataset
    v = x['review_count']
    r = x['stars']
    score = (v/(v+m))*r + (m/(v+m))*C
    return score

In [7]:
C = phila_res_df['stars'].mean()
m = phila_res_df['review_count'].quantile(0.90) 
new_df = phila_res_df.copy().loc[phila_res_df['review_count'] >= m]
new_df['weight_score'] = compute_wr(new_df, m, C)
new_df

,business_id,name,city,state,stars,review_count,is_open,attributes,categories,weight_score
19,dChRGpit9fM_kZK5pafNyA,The Love,Philadelphia,PA,4.0,618,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, American (New), Breakfast & Brunc...",3.862011
20,QWqKTWQ2OiDgo3dzNkpung,Jong Ka Jib,Philadelphia,PA,4.5,351,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Korean, Restaurants",4.082207
21,7mpYTDb24SywNMRn3yeakQ,The Twisted Tail,Philadelphia,PA,4.0,604,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Event Planning & Services, Whiskey Bars, Ameri...",3.859823
35,JomDoQafikclSVVCPkWjnA,Cedar Park Cafe,Philadelphia,PA,4.0,301,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Diners, Restaurants, Sandwiches, Breakfast & B...",3.786554
47,V6Om7YZhlRQRU7WfuxHq8Q,Beck's Cajun Cafe,Philadelphia,PA,4.0,485,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Cajun/Creole",3.837980
...,...,...,...,...,...,...,...,...,...,...
5799,hUmHwBQtGg0iH-PZakQJDw,Wm Mulherin's Sons,Philadelphia,PA,4.5,610,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Tapas/Small Plates, Italian, Szec...",4.203967
5809,0RuvlgTnKFbX3IK0ZOOocA,Green Eggs Café,Philadelphia,PA,4.0,2679,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, American (New), Diners, Breakfast...",3.958165
5822,ZGH8MzJa7Q7iIpmtzBAJAQ,Manayunk Brewery,Philadelphia,PA,3.5,692,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sushi Bars, American (New), Bars, Pizza, Ameri...",3.516087
5827,C9UylQTOh7uwZo4a7QhLyg,Friday Saturday Sunday,Philadelphia,PA,4.5,287,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","American (New), Restaurants, Salad, Seafood",4.034940
5833,eLi0bpsDoWQkBhJX1d46tg,Fergie's Pub,Philadelphia,PA,3.5,286,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Event Planning & Services, Bars, Pubs, Nightli...",3.527653

**I picked out the 90% upper quantile of the data to filter restaurants that have too few reviews to be useful**

- Since the dataset contains restaurant with a 5 stars reviews, it is realistically unlikely. But there are several reasons as to why this happens:
    1. The restaurant is too new or has too few reviews to best represent the establishment
    2. The restaurents' reviews are likely fabricated
- Either way, restaurants with too few reviews is not likely to yield useful insights
- From a specific set of restaurants, I computed the weight rating of the entire dataset to return a the best restaurants in the data.

In [8]:
baseline_recommendation = new_df.sort_values("weight_score", ascending= False)
baseline_recommendation.head(10)

,business_id,name,city,state,stars,review_count,is_open,attributes,categories,weight_score
5550,ytynqOUb3hjKeJfRj5Tshw,Reading Terminal Market,Philadelphia,PA,4.5,5721,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Candy Stores, Shopping, Department Stores, Fas...",4.456150
1262,ctHjyadbDQAtUFfkcAFEHw,Zahav,Philadelphia,PA,4.5,3065,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Nightlife, Bars, Food, Ethnic Food, Middle Eas...",4.421319
2531,6ajnOk0GcY9xbb5Ocaw8Gw,Barbuzzo,Philadelphia,PA,4.5,2893,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Mediterranean, Restaurants, Pizza, Italian",4.417053
3836,i_FWONQD1ZBqrNE2b-M5Ug,Talula's Garden,Philadelphia,PA,4.5,1927,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","American (New), Restaurants",4.380725
3487,6_T2xzR74JqGCTPefAD8Tw,Morimoto,Philadelphia,PA,4.5,1914,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Japanese, American (Traditional), American (Ne...",4.380018
845,Sv1MEZP-mMfp8SmE0hwYEA,Terakawa Ramen,Philadelphia,PA,4.5,1693,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Japanese, Ramen, Ethnic Food, Restaurants, Loc...",4.366570
716,LM54ufrINJWoTN5imV8Etw,John's Roast Pork,Philadelphia,PA,4.5,1564,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sandwiches, Salad, American (Traditional), Che...",4.357229
5708,K7KHmHzxNwzqiijSJeKe_A,Cafe La Maude,Philadelphia,PA,4.5,1485,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Sandwiches, Cafes, Coffee & Tea, Restaurants, ...",4.350834
5739,2CDI713ATuxHfnB5b-sBdw,Vedge,Philadelphia,PA,4.5,1447,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Restaurants, Vegetarian, Beer, Wine & Spirits,...",4.347549
5097,atZ_olNKXOG4rEr6mccN8g,Beiler's Bakery,Philadelphia,PA,4.5,1368,1,"{'AcceptsInsurance': None, 'AgesAllowed': None...","Food, Donuts, Food Stands, Restaurants, Specia...",4.340235

The output above returns top 10 best restaurant in Philadelphia, with their respective weight score on the far right. As we can see, these top restaurants are not tailored or personalized to best represent a user's interest, however this recommendation would be a greate baseline to measure other semantic and sentimental model againts.

In [9]:
global_res_df = pd.read_parquet("../data/restaurant_global.parquet")
global_c = global_res_df['stars'].mean()
global_m = global_res_df['review_count'].quantile(0.90) 
new_global_df = global_res_df.copy().loc[global_res_df['review_count'] >= global_m]
new_global_df

,business_id,name,city,state,stars,review_count,is_open,attributes,categories
7,MUTTqe8uqyMdBl186RmNeA,Tuna Bar,Philadelphia,PA,4.0,245,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Sushi Bars, Restaurants, Japanese"
11,9OG5YkX1g2GReZM0AskizA,Romano's Macaroni Grill,Reno,NV,2.5,339,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Restaurants, Italian"
28,seKihQKpGGnCeLuELRQPSQ,Twin Peaks,Indianapolis,IN,3.5,257,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Sports Bars, American (New), American (Traditi..."
37,IDtLPgUrqorrpqSLdfMhZQ,Helena Avenue Bakery,Santa Barbara,CA,4.0,389,1,"{'RestaurantsDelivery': 'None', 'OutdoorSeatin...","Food, Restaurants, Salad, Coffee & Tea, Breakf..."
38,YNjyv0gfOr2g8lbmUpTnKg,Copper Vine,New Orleans,LA,4.5,350,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Nightlife, Pubs, Event Planning & Services, Wi..."
...,...,...,...,...,...,...,...,...,...
52248,XtuWejrrZMZGkRMxxesKJw,Johnny Grits Southern Fresh,New Port Richey,FL,3.5,224,0,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Breakfast & Brunch, Restaurants, Comfort Food,..."
52255,8MzF1Tlgz0pOkxmhP5dYzA,El Cap Restaurant,St. Petersburg,FL,3.5,414,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","American (Traditional), Burgers, Restaurants"
52256,Ld3qgGua7MqrFnZY8AIo0A,Café Ventana,Saint Louis,MO,3.5,290,0,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Food, Breakfast & Brunch, Cajun/Creole, Restau..."
52271,uriD7RFuHhLJeDdKaf0nFA,Pizza Guru,Santa Barbara,CA,4.0,299,0,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Restaurants, Pizza, Food"
52280,w_4xUt-1AyY2ZwKtnjW0Xg,Bittercreek Alehouse,Boise,ID,4.5,998,1,"{'RestaurantsDelivery': 'None', 'OutdoorSeatin...","Bars, Gastropubs, Sandwiches, Nightlife, Resta..."

In [10]:
new_global_df['weight_score'] = compute_wr(new_global_df, global_m, global_c)
global_baseline_recommendation = new_global_df.sort_values("weight_score", ascending= False)
global_baseline_recommendation.head(10)

,business_id,name,city,state,stars,review_count,is_open,attributes,categories,weight_score
4259,_aKr7POnacW_VizRKBpCiA,Blues City Deli,Saint Louis,MO,5.0,991,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Delis, Bars, Restaurants, Nightlife, Pubs, Ame...",4.743963
46629,8QqnRpM-QxGsjDNuu0E57A,Carlillos Cocina,Sparks,NV,5.0,799,1,"{'RestaurantsDelivery': 'None', 'OutdoorSeatin...","Bars, Mexican, Breakfast & Brunch, Restaurants...",4.695073
5742,DVBJRvnCpkqaYl6nHroaMg,Tumerico,Tucson,AZ,5.0,705,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Mexican, Gluten-Free, Vegetarian, Restaurants,...",4.663627
24421,gP_oWJykA2RocIs_GurKWQ,Yats,Franklin,TN,5.0,623,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Cajun/Creole, Restaurants, Caterers, Comfort F...",4.630375
43661,OR7VJQ3Nk1wCcIbPN4TCQQ,Smiling With Hope Pizza,Reno,NV,5.0,526,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Italian, Restaurants, Salad, Pizza",4.581428
50341,FHDuu5Mv1bEkusxEuhptZQ,Barracuda Deli Cafe St. Pete Beach,St Pete Beach,FL,5.0,521,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Caribbean, Latin American, Restaurants, Breakf...",4.578551
2799,D9p7-HsY9llYP3BaCVg4DA,Cafe Soleil,St. Pete Beach,FL,5.0,468,1,"{'RestaurantsDelivery': 'None', 'OutdoorSeatin...","Restaurants, French, Coffee & Tea, Bakeries, B...",4.545435
11625,tARR9jhv5gi9TjsfSVmjmw,Kaffe Crepe,Reno,NV,5.0,454,1,"{'RestaurantsDelivery': 'False', 'OutdoorSeati...","Food, Restaurants, Cafes, Creperies, Coffee & Tea",4.535800
51676,vyOVT4bcW227LRwJGHTeSw,Buena Onda,Santa Barbara,CA,5.0,414,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Event Planning & Services, Latin American, Cat...",4.505875
33041,xBPg6gzunjpEUT6FiRrpog,Big Al's Deli,Nashville,TN,5.0,390,1,"{'RestaurantsDelivery': 'True', 'OutdoorSeatin...","Restaurants, Delis, Southern",4.485995

The outpute above is the popularity restaurant (Top 10 best rating establishments) on the global dataset. I will also use this as a baseline to measure against the popularity model (focus on the city Philadelphia) and other models